In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [23]:
personality = pd.read_excel("../../Datasets/Personality Survey Data.xlsx")

In [24]:
buyback_contract = personality.iloc[51:95, :]
buyback_contract = buyback_contract.iloc[:,2:]
buyback_contract.columns = personality.iloc[50, 2:]
buyback_contract.reset_index(drop=True, inplace = True)

In [25]:
buyback_contract.columns

Index(['PLAYER NAME', 'Faculty', 'Program', 'Grad/ Undergrad', 'ENS 208',
       'MS 401', 'Other Supply Chain Course?'],
      dtype='object', name=50)

In [26]:
buyback_contract

50,PLAYER NAME,Faculty,Program,Grad/ Undergrad,ENS 208,MS 401,Other Supply Chain Course?
0,manufacturer1,FENS,NaN,Undergrad,YES,NaN,NaN
1,manufacturer2,FENS,MSIE,Undergrad,YES,YES,YES
2,manufacturer3,FENS,MSIE,Undergrad,YES,NaN,YES
3,manufacturer4,FENS,MSIE,Undergrad,YES,YES,NaN
4,manufacturer5,FENS,MSIE,Undergrad,YES,NaN,NaN
5,manufacturer6,FENS,MSIE,Undergrad,YES,YES,NaN
6,manufacturer7,FENS,MSIE,Undergrad,YES,YES,YES
7,manufacturer8,SOM,MAN,Undergrad,YES,NaN,NaN
8,manufacturer9,FENS,MSIE,Undergrad,YES,NaN,NaN
9,manufacturer10,FENS,MSIE,Undergrad,YES,NaN,YES
10,manufacturer11,FENS,MSIE,Undergrad,YES,YES,YES
11,manufacturer12,FENS,MSIE,Undergrad,YES,YES,YES
12,manufacturer13,FENS,MSIE,Undergrad,YES,YES,NaN
13,manufacturer14,FENS,MSIE,Undergrad,YES,YES,YES
14,manufacturer15,FENS,NaN,Undergrad,NaN,NaN,NaN
15,manufacturer16,FASS,ECON,PhD,NaN,NaN,NaN
16,manufacturer17,FENS,MSIE,Undergrad,YES,NaN,NaN
17,manufacturer18,FENS,NaN,Undergrad,YES,NaN,NaN
18,manufacturer19,FENS,IE,PhD,NaN,NaN,YES
19,manufacturer20,FENS,NaN,Undergrad,NaN,NaN,NaN
20,manufacturer21,FENS,NaN,Undergrad,NaN,NaN,NaN
21,manufacturer22,FENS,IE,MS/MA,YES,YES,YES
22,retailer1,FENS,IE,MS/MA,NaN,NaN,YES
23,retailer2,FENS,EE,Undergrad,NaN,NaN,NaN
24,retailer3,FENS,MAT,Undergrad,NaN,NaN,NaN
25,retailer4,FENS,IE,MS/MA,NaN,NaN,NaN
26,retailer5,FENS,MSIE,Undergrad,YES,YES,YES
27,retailer6,FENS,NaN,Undergrad,NaN,NaN,NaN
28,retailer7,FASS,ECON,MS/MA,NaN,NaN,NaN
29,retailer8,FENS,MSIE,Undergrad,YES,YES,NaN
30,retailer9,FENS,IE,Undergrad,YES,YES,YES
31,retailer10,FENS,MSIE,Undergrad,YES,YES,NaN
32,retailer11,SOM,NaN,Undergrad,NaN,NaN,NaN
33,retailer12,FENS,MSIE,Undergrad,YES,YES,YES
34,retailer13,FASS,ECON,Undergrad,NaN,NaN,NaN
35,retailer14,FENS,NaN,Undergrad,YES,NaN,NaN
36,retailer15,SOM,NaN,Undergrad,NaN,NaN,NaN
37,retailer16,FENS,MSIE,Undergrad,YES,NaN,NaN
38,retailer17,FENS,MSIR,Undergrad,YES,YES,YES
39,retailer18,FENS,IE,PhD,YES,YES,YES
40,retailer19,FASS,Public Pols,Undergrad,NaN,NaN,NaN
41,retailer20,FENS,NaN,Undergrad,NaN,NaN,NaN
42,retailer21,FENS,NaN,Undergrad,YES,NaN,NaN
43,retailer22,FENS,IE,MS/MA,NaN,NaN,NaN

In [27]:
faculty = pd.get_dummies(buyback_contract['Faculty'])
faculty = faculty.replace({True: 1, False: 0})
faculty.columns = ['faculty_' + col for col in faculty.columns]
buyback_contract = pd.concat([buyback_contract, faculty], axis=1)
buyback_contract.drop(["Faculty"], axis=1,inplace = True)

buyback_contract

,PLAYER NAME,Program,Grad/ Undergrad,ENS 208,MS 401,Other Supply Chain Course?,faculty_FASS,faculty_FENS,faculty_SOM
0,manufacturer1,NaN,Undergrad,YES,NaN,NaN,0,1,0
1,manufacturer2,MSIE,Undergrad,YES,YES,YES,0,1,0
2,manufacturer3,MSIE,Undergrad,YES,NaN,YES,0,1,0
3,manufacturer4,MSIE,Undergrad,YES,YES,NaN,0,1,0
4,manufacturer5,MSIE,Undergrad,YES,NaN,NaN,0,1,0
5,manufacturer6,MSIE,Undergrad,YES,YES,NaN,0,1,0
6,manufacturer7,MSIE,Undergrad,YES,YES,YES,0,1,0
7,manufacturer8,MAN,Undergrad,YES,NaN,NaN,0,0,1
8,manufacturer9,MSIE,Undergrad,YES,NaN,NaN,0,1,0
9,manufacturer10,MSIE,Undergrad,YES,NaN,YES,0,1,0
10,manufacturer11,MSIE,Undergrad,YES,YES,YES,0,1,0
11,manufacturer12,MSIE,Undergrad,YES,YES,YES,0,1,0
12,manufacturer13,MSIE,Undergrad,YES,YES,NaN,0,1,0
13,manufacturer14,MSIE,Undergrad,YES,YES,YES,0,1,0
14,manufacturer15,NaN,Undergrad,NaN,NaN,NaN,0,1,0
15,manufacturer16,ECON,PhD,NaN,NaN,NaN,1,0,0
16,manufacturer17,MSIE,Undergrad,YES,NaN,NaN,0,1,0
17,manufacturer18,NaN,Undergrad,YES,NaN,NaN,0,1,0
18,manufacturer19,IE,PhD,NaN,NaN,YES,0,1,0
19,manufacturer20,NaN,Undergrad,NaN,NaN,NaN,0,1,0
20,manufacturer21,NaN,Undergrad,NaN,NaN,NaN,0,1,0
21,manufacturer22,IE,MS/MA,YES,YES,YES,0,1,0
22,retailer1,IE,MS/MA,NaN,NaN,YES,0,1,0
23,retailer2,EE,Undergrad,NaN,NaN,NaN,0,1,0
24,retailer3,MAT,Undergrad,NaN,NaN,NaN,0,1,0
25,retailer4,IE,MS/MA,NaN,NaN,NaN,0,1,0
26,retailer5,MSIE,Undergrad,YES,YES,YES,0,1,0
27,retailer6,NaN,Undergrad,NaN,NaN,NaN,0,1,0
28,retailer7,ECON,MS/MA,NaN,NaN,NaN,1,0,0
29,retailer8,MSIE,Undergrad,YES,YES,NaN,0,1,0
30,retailer9,IE,Undergrad,YES,YES,YES,0,1,0
31,retailer10,MSIE,Undergrad,YES,YES,NaN,0,1,0
32,retailer11,NaN,Undergrad,NaN,NaN,NaN,0,0,1
33,retailer12,MSIE,Undergrad,YES,YES,YES,0,1,0
34,retailer13,ECON,Undergrad,NaN,NaN,NaN,1,0,0
35,retailer14,NaN,Undergrad,YES,NaN,NaN,0,1,0
36,retailer15,NaN,Undergrad,NaN,NaN,NaN,0,0,1
37,retailer16,MSIE,Undergrad,YES,NaN,NaN,0,1,0
38,retailer17,MSIR,Undergrad,YES,YES,YES,0,1,0
39,retailer18,IE,PhD,YES,YES,YES,0,1,0
40,retailer19,Public Pols,Undergrad,NaN,NaN,NaN,1,0,0
41,retailer20,NaN,Undergrad,NaN,NaN,NaN,0,1,0
42,retailer21,NaN,Undergrad,YES,NaN,NaN,0,1,0
43,retailer22,IE,MS/MA,NaN,NaN,NaN,0,1,0

In [28]:
program = pd.get_dummies(buyback_contract['Program'])
program = program.replace({True: 1, False: 0, })
program.columns = ['program_' + col for col in program.columns]
buyback_contract = pd.concat([buyback_contract, program], axis=1)
buyback_contract.drop(["Program"], axis=1,inplace = True)

In [29]:

Grad_Undergrad = pd.get_dummies(buyback_contract['Grad/ Undergrad'])
Grad_Undergrad = Grad_Undergrad.replace({True: 1, False: 0})
Grad_Undergrad.columns = ['Grad_Undergrad_' + col for col in Grad_Undergrad.columns]
buyback_contract = pd.concat([buyback_contract, Grad_Undergrad], axis=1)
buyback_contract.drop(["Grad/ Undergrad"], axis=1,inplace = True)

In [30]:



buyback_contract["ENS 208"] = buyback_contract["ENS 208"].replace({"YES": 1, np.nan: 0}).astype(int)
buyback_contract["MS 401"] = buyback_contract["MS 401"].replace({"YES": 1, np.nan: 0}).astype(int)
buyback_contract["Other Supply Chain Course?"] = buyback_contract["Other Supply Chain Course?"].replace({"YES": 1, np.nan: 0}).astype(int)
buyback_contract

,PLAYER NAME,ENS 208,MS 401,Other Supply Chain Course?,faculty_FASS,faculty_FENS,faculty_SOM,program_ECON,program_EE,program_IE,program_MAN,program_MAT,program_MSIE,program_MSIR,program_Public Pols,Grad_Undergrad_MS/MA,Grad_Undergrad_PhD,Grad_Undergrad_Undergrad
0,manufacturer1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
1,manufacturer2,1,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1
2,manufacturer3,1,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1
3,manufacturer4,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1
4,manufacturer5,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1
5,manufacturer6,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1
6,manufacturer7,1,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1
7,manufacturer8,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1
8,manufacturer9,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1
9,manufacturer10,1,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1
10,manufacturer11,1,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1
11,manufacturer12,1,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1
12,manufacturer13,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1
13,manufacturer14,1,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1
14,manufacturer15,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
15,manufacturer16,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0
16,manufacturer17,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1
17,manufacturer18,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
18,manufacturer19,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0
19,manufacturer20,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
20,manufacturer21,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
21,manufacturer22,1,1,1,0,1,0,0,0,1,0,0,0,0,0,1,0,0
22,retailer1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,1,0,0
23,retailer2,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1
24,retailer3,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1
25,retailer4,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0
26,retailer5,1,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1
27,retailer6,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
28,retailer7,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0
29,retailer8,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1
30,retailer9,1,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1
31,retailer10,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1
32,retailer11,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
33,retailer12,1,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1
34,retailer13,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1
35,retailer14,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
36,retailer15,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
37,retailer16,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1
38,retailer17,1,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1
39,retailer18,1,1,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0
40,retailer19,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1
41,retailer20,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
42,retailer21,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1
43,retailer22,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0

In [31]:
buyback_contract.to_csv('../../Datasets/buyback_contract_subject_background_information.csv', index=False)

In [3]:
post_experiment = pd.read_excel("../../Datasets/Personality Survey Data.xlsx", sheet_name="Post-Experiment Surveys")

In [8]:
post_experiment

,Unnamed: 0,Unnamed: 1,WHOLESALE PRICE CONTRACT,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47
0,NaN,NaN,NaN,Please indicate how much each of the below fac...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,PLAYER NAME,Changes in the consumer demand,Manufacturer's wholesale price,My expected profit from the decision support tool,Manufacturer's expected profit from the decisi...,My profit in the previous period,Manufacturer's profit in the previous period,Manufacturer's profit being higher than mine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,manufacturer1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,manufacturer2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,manufacturer3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,NaN,18.0,ret18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Karlarımı düşürdü.,Daha kısıtlı hissettirdi. Sonuçta bir şekilde ...,0 sipariş vererek.,Gözü çok açtı. Hiç inmedi.,NaN,Hayır,Evet,Evet,Hayır. (Anket gönderilecek.),NaN
292,NaN,19.0,ret19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Daha uzun süre boyunca karım ve zararım sıfır ...,Daha güçlü hissettirdi. Çünkü bu sayede yüksek...,"Taleplerimi 0, 51 ya da 60 olarak tutarak.",Manufacturer bana 8 ve üstü toptan fiyatlar ve...,Bir keresinde yanlış olarak 0 gönderdiğğim içi...,Evet,Evet,Evet,Hayır. (Anket gönderilecek.),NaN
293,NaN,20.0,ret20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,manufacturer bana iki kez yüksek fiyat yolladı...,Bu onun gönderdiği fiyata bağlı birşey aslında...,Onun karını düşürecek şekilde belirlerdim bunu...,Daha deneysel bir yol izledi sanırım çünkü 7 v...,NaN,Evet,Evet,Evet,Hayır. (Anket gönderilecek.),NaN
294,NaN,21.0,ret21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Manufacture'ın bir dahaki periyot için daha kü...,Daha kısıtlı,Normalde 0 vermeyi düşündüm fakat kendi karım ...,ilk başta random sayılar veriyordu daha sonra ...,NaN,Evet,Evet,Hayır,Hayır. (Anket gönderilecek.),NaN
295,NaN,22.0,ret22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0 sipariş verdiğim takdirde benim de kar payım...,Kendimi kısıtlı hissettim çünkü consumer sayıs...,Talebimi düşürdüm ama bunu yaparken elde edece...,Eşleştirilmiş olduğum manufacturer cost konusu...,NaN,Evet,Evet,Evet,Hayır. (Anket gönderilecek.),NaN

In [88]:
buyback_contract_post_experiment = post_experiment.iloc[51:95,2:25]

buyback_contract_post_experiment.columns = post_experiment.iloc[50,2:25]
buyback_contract_post_experiment.reset_index(drop=True, inplace=True)

In [91]:
buyback_contract_post_experiment_manufacturer = buyback_contract_post_experiment.iloc[:22,12:26]
buyback_contract_post_experiment_manufacturer

50,Changes in the consumer demand.,My expected profit from the decision support tool.,Retailer's expected profit from the decision support tool.,Retailer's stock quantity decision in the previous period.,My profit in the previous period.,Retailer's profit in the previous period.,Retailer's profit being higher than mine.,Retailer's profit being lower than mine.,Retailer's loss. (negative profit),Retailer's rejections of the contract by placing 0 orders.,My cumulative profit.
0,Affected a little,Affected a lot,Affected,Affected,Affected,Affected a little,Didn't affect,Didn't affect,Didn't affect,Didn't affect,Affected
1,Affected a lot,Affected a lot,Affected,Affected a lot,Affected,Affected a little,Affected a little,Affected a little,Affected a little,Affected a lot,Affected a little
2,Affected a little,Affected a little,Affected a little,Didn't affect,Affected a little,Affected,Affected a lot,Affected a lot,Affected a little,Affected a lot,Affected
3,Affected a lot,Affected a lot,Affected a lot,Affected a lot,Affected,Affected,Affected,Affected,Affected,Affected,Didn't affect
4,Affected,Affected,Affected,Affected,Affected a little,Affected a little,Didn't affect,Didn't affect,Didn't affect,Affected,Didn't affect
5,Affected,Affected,Affected a lot,Affected a little,Affected a little,Affected a little,Affected a little,Affected a little,Affected,Affected,Affected a lot
6,Affected,Affected,Affected,Affected a lot,Affected,Affected a little,Affected,Affected,Affected,Affected a lot,Affected a little
7,Affected a little,Affected,Affected,Affected a lot,Affected a lot,Affected a little,Didn't affect,Affected a little,Affected a little,Affected a lot,Affected a little
8,Affected,Affected,Affected,Affected a lot,Affected a lot,Affected,Didn't affect,Didn't affect,Didn't affect,Affected a little,Affected
9,Affected,Affected a lot,Didn't affect,Affected,Affected a lot,Didn't affect,Affected a little,Didn't affect,Didn't affect,Affected a lot,Affected
10,Didn't affect,Affected a lot,Affected,Affected a lot,Affected a little,Affected a little,Affected a little,Affected a little,Affected,Affected,Didn't affect
11,Affected a little,Affected a little,Affected,Affected a lot,Didn't affect,Affected a little,Didn't affect,Didn't affect,Didn't affect,Affected a little,Affected a little
12,Affected,NaN,Affected a little,Affected a little,Affected,Didn't affect,Didn't affect,Didn't affect,Didn't affect,Affected a lot,Affected a lot
13,Affected,Affected,Affected a little,Affected a lot,Affected,Affected a little,Affected a little,Affected a little,Affected a lot,Affected a lot,Affected
14,Affected,Affected a lot,Affected a little,Affected a little,Affected,Affected a little,Didn't affect,Didn't affect,Didn't affect,Affected a lot,Affected a lot
15,Affected a little,Etkilemedi,Etkilemedi,Affected a little,Etkilemedi,Affected a little,Etkilemedi,Etkilemedi,Affected,Affected,Etkilemedi
16,Affected a little,Affected,Affected a little,Affected,Affected,Didn't affect,Didn't affect,Didn't affect,Affected a little,Affected,Affected a little
17,Affected a little,Didn't affect,Affected a little,Affected,Affected a little,Didn't affect,Didn't affect,Didn't affect,Affected a little,Affected,Didn't affect
18,Affected a little,Affected a little,Affected,Affected a lot,Affected,Affected,Etkilemedi,Affected a little,Affected,Affected,Affected a little
19,Affected,Affected,Affected a little,Affected a lot,Affected a lot,Affected a little,Didn't affect,Didn't affect,Didn't affect,Affected a lot,Didn't affect
20,Affected a little,Affected,Didn't affect,Didn't affect,Affected,Didn't affect,Didn't affect,Affected,Didn't affect,Affected a lot,Affected a lot
21,Affected a little,Affected a little,Affected a little,Affected,Affected,Affected a little,Didn't affect,Didn't affect,Affected a little,Affected a lot,Affected

In [94]:
def changer(feature_name, dataset_name):
    dataset_name[feature_name] = dataset_name[feature_name].replace(
        {
            "Affected a lot": 3,
            "Affected": 2,
            "Affected a little": 1,
            "Didn't affect": 0,
            np.nan: -1,
            "Etkilemedi":0
            
        }
    ).astype(int)

In [95]:
for i in buyback_contract_post_experiment_manufacturer.columns:
    changer(i, buyback_contract_post_experiment_manufacturer)
buyback_contract_post_experiment_manufacturer = pd.concat([buyback_contract_post_experiment_manufacturer, buyback_contract_post_experiment.iloc[0:22,0]], axis =1)
buyback_contract_post_experiment_manufacturer

,Changes in the consumer demand.,My expected profit from the decision support tool.,Retailer's expected profit from the decision support tool.,Retailer's stock quantity decision in the previous period.,My profit in the previous period.,Retailer's profit in the previous period.,Retailer's profit being higher than mine.,Retailer's profit being lower than mine.,Retailer's loss. (negative profit),Retailer's rejections of the contract by placing 0 orders.,My cumulative profit.,PLAYER NAME
0,1,3,2,2,2,1,0,0,0,0,2,manufacturer1
1,3,3,2,3,2,1,1,1,1,3,1,manufacturer2
2,1,1,1,0,1,2,3,3,1,3,2,manufacturer3
3,3,3,3,3,2,2,2,2,2,2,0,manufacturer4
4,2,2,2,2,1,1,0,0,0,2,0,manufacturer5
5,2,2,3,1,1,1,1,1,2,2,3,manufacturer6
6,2,2,2,3,2,1,2,2,2,3,1,manufacturer7
7,1,2,2,3,3,1,0,1,1,3,1,manufacturer8
8,2,2,2,3,3,2,0,0,0,1,2,manufacturer9
9,2,3,0,2,3,0,1,0,0,3,2,manufacturer10
10,0,3,2,3,1,1,1,1,2,2,0,manufacturer11
11,1,1,2,3,0,1,0,0,0,1,1,manufacturer12
12,2,-1,1,1,2,0,0,0,0,3,3,manufacturer13
13,2,2,1,3,2,1,1,1,3,3,2,manufacturer14
14,2,3,1,1,2,1,0,0,0,3,3,manufacturer15
15,1,0,0,1,0,1,0,0,2,2,0,manufacturer16
16,1,2,1,2,2,0,0,0,1,2,1,manufacturer17
17,1,0,1,2,1,0,0,0,1,2,0,manufacturer18
18,1,1,2,3,2,2,0,1,2,2,1,manufacturer19
19,2,2,1,3,3,1,0,0,0,3,0,manufacturer20
20,1,2,0,0,2,0,0,2,0,3,3,manufacturer21
21,1,1,1,2,2,1,0,0,1,3,2,manufacturer22

In [96]:
buyback_contract_post_experiment_manufacturer.to_csv('../../Datasets/buyback_contract_post_experiment_manufacturer.csv', index=False)

In [103]:
buyback_contract_post_experiment_retailer = buyback_contract_post_experiment.iloc[22:,:12]
buyback_contract_post_experiment_retailer

50,PLAYER NAME,Changes in the consumer demand,Manufacturer's wholesale price,Manufacturer's buyback price,My expected profit from the decision support tool,Manufacturer's expected profit from the decision support tool,My profit in the previous period,Manufacturer's profit in the previous period,Manufacturer's profit being higher than mine,Manufacturer's profit being lower than mine,Manufacturer's loss (negative profit),My cumulative profit
22,retailer1,Affected a little,Affected a lot,Affected a lot,Affected a lot,Didn't affect,Didn't affect,Didn't affect,Didn't affect,Didn't affect,Didn't affect,Affected
23,retailer2,Affected,Affected a lot,Affected a lot,Affected,Affected,Didn't affect,Didn't affect,Affected,Affected a little,Didn't affect,Affected a little
24,retailer3,Didn't affect,Affected a lot,Affected a little,Affected,Affected a lot,Didn't affect,Affected,Didn't affect,Didn't affect,Affected,Affected a lot
25,retailer4,Affected a lot,Affected,Affected a lot,Affected,Affected a little,Didn't affect,Didn't affect,Didn't affect,Didn't affect,Didn't affect,Didn't affect
26,retailer5,Affected,Affected a lot,Affected a little,Affected a lot,Affected a lot,Affected,Affected,Affected a lot,Affected a lot,Affected a lot,Affected a little
27,retailer6,Affected,Affected,Affected,Affected a lot,Affected a lot,Affected a little,Affected a little,Affected a lot,Affected a lot,Affected,Affected a lot
28,retailer7,Didn't affect,Affected a lot,Affected a lot,Affected a little,Affected a little,Didn't affect,Didn't affect,Affected a little,Affected a little,Didn't affect,Affected a little
29,retailer8,Affected a little,Affected a lot,Affected,Affected,Affected,Didn't affect,Didn't affect,Affected,Affected,Didn't affect,Affected a little
30,retailer9,Affected,Affected a lot,Affected a lot,Affected a little,Affected a little,Affected a little,Affected a little,Affected a little,Didn't affect,Affected a little,Didn't affect
31,retailer10,Affected a little,Affected,Affected,Affected a lot,Affected a lot,Affected,Affected a little,Affected a lot,Affected a little,Didn't affect,Affected a little
32,retailer11,Affected,Affected a lot,Didn't affect,Affected,NaN,Affected a lot,Affected a little,Affected a lot,Didn't affect,Affected a lot,Affected
33,retailer12,Affected a lot,Affected a lot,Affected,Affected a lot,Affected a little,Affected,Affected a little,Affected a little,Didn't affect,Didn't affect,Affected a lot
34,retailer13,Affected a little,Affected a lot,Affected a lot,Affected a lot,Affected,Didn't affect,Affected a little,Affected,Affected a little,Affected a little,Didn't affect
35,retailer14,Affected a little,Affected a lot,Affected a lot,Affected a lot,Affected a little,Affected a little,Didn't affect,Affected a little,Didn't affect,Didn't affect,Affected
36,retailer15,Affected,Affected a lot,Affected a little,Affected a lot,Didn't affect,Affected,Didn't affect,Affected a little,Didn't affect,Didn't affect,Didn't affect
37,retailer16,Affected,Affected a lot,Affected,Affected,Affected,Affected,Didn't affect,Affected a little,Didn't affect,Didn't affect,Affected a lot
38,retailer17,Affected a little,Affected a lot,Affected a little,Affected a lot,Affected a little,Didn't affect,Didn't affect,Didn't affect,Didn't affect,Didn't affect,Affected a little
39,retailer18,Affected,Affected,Affected,Affected,Affected a little,Didn't affect,Didn't affect,Didn't affect,Didn't affect,Affected a little,Didn't affect
40,retailer19,Affected,Affected,Affected a little,Etkilemedi,Etkilemedi,Etkilemedi,Etkilemedi,Etkilemedi,Etkilemedi,Etkilemedi,Affected
41,retailer20,Affected a little,Affected,Affected,Affected,Affected a little,Didn't affect,Didn't affect,Affected,Didn't affect,Didn't affect,Affected a little
42,retailer21,Affected a little,Affected a lot,Affected,Affected a lot,Affected a lot,Affected a little,Affected a little,Affected,Didn't affect,Didn't affect,Affected
43,retailer22,Affected a little,Affected,Affected,Affected,Affected a little,Affected a little,Didn't affect,Affected a little,Affected a little,Didn't affect,Affected

In [104]:
for i in buyback_contract_post_experiment_retailer.columns[1:]:
    changer(i, buyback_contract_post_experiment_retailer)

buyback_contract_post_experiment_retailer.reset_index(drop=True, inplace=True)
buyback_contract_post_experiment_retailer

50,PLAYER NAME,Changes in the consumer demand,Manufacturer's wholesale price,Manufacturer's buyback price,My expected profit from the decision support tool,Manufacturer's expected profit from the decision support tool,My profit in the previous period,Manufacturer's profit in the previous period,Manufacturer's profit being higher than mine,Manufacturer's profit being lower than mine,Manufacturer's loss (negative profit),My cumulative profit
0,retailer1,1,3,3,3,0,0,0,0,0,0,2
1,retailer2,2,3,3,2,2,0,0,2,1,0,1
2,retailer3,0,3,1,2,3,0,2,0,0,2,3
3,retailer4,3,2,3,2,1,0,0,0,0,0,0
4,retailer5,2,3,1,3,3,2,2,3,3,3,1
5,retailer6,2,2,2,3,3,1,1,3,3,2,3
6,retailer7,0,3,3,1,1,0,0,1,1,0,1
7,retailer8,1,3,2,2,2,0,0,2,2,0,1
8,retailer9,2,3,3,1,1,1,1,1,0,1,0
9,retailer10,1,2,2,3,3,2,1,3,1,0,1
10,retailer11,2,3,0,2,-1,3,1,3,0,3,2
11,retailer12,3,3,2,3,1,2,1,1,0,0,3
12,retailer13,1,3,3,3,2,0,1,2,1,1,0
13,retailer14,1,3,3,3,1,1,0,1,0,0,2
14,retailer15,2,3,1,3,0,2,0,1,0,0,0
15,retailer16,2,3,2,2,2,2,0,1,0,0,3
16,retailer17,1,3,1,3,1,0,0,0,0,0,1
17,retailer18,2,2,2,2,1,0,0,0,0,1,0
18,retailer19,2,2,1,0,0,0,0,0,0,0,2
19,retailer20,1,2,2,2,1,0,0,2,0,0,1
20,retailer21,1,3,2,3,3,1,1,2,0,0,2
21,retailer22,1,2,2,2,1,1,0,1,1,0,2

In [106]:
buyback_contract_post_experiment_retailer.to_csv("../../Datasets/buyback_contract_post_experiment_retailer.csv", index=False)