In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
personality = pd.read_excel("../../Datasets/Personality Survey Data.xlsx")

In [14]:
default_contract = personality.iloc[152:196, :]
default_contract = default_contract.iloc[:,2:]
default_contract.columns = personality.iloc[50, 2:]
default_contract.reset_index(drop=True, inplace = True)

In [15]:
default_contract

50,PLAYER NAME,Faculty,Program,Grad/ Undergrad,ENS 208,MS 401,Other Supply Chain Course?
0,manufacturer1,SOM,undeclared,Undergraduate,YES,NaN,NaN
1,manufacturer2,FENS,Henuz yok,Undergraduate,YES,NaN,YES
2,manufacturer3,FENS,Have not decleration yet.,Undergraduate,YES,NaN,YES
3,manufacturer4,FENS,Mühendislik ve Doğa Bilimleri,Undergraduate,YES,NaN,NaN
4,manufacturer5,FENS,MS,Undergraduate,YES,NaN,NaN
5,manufacturer6,FENS,MECHATRONICS,Undergraduate,NaN,NaN,NaN
6,manufacturer7,FENS,Manufacturing System Engineering,Undergraduate,YES,NaN,YES
7,manufacturer8,FENS,mekatronics engineering,Undergraduate,NaN,NaN,NaN
8,manufacturer9,FENS,ms,Undergraduate,YES,NaN,NaN
9,manufacturer10,FENS,Manufacturing Systems Engineering,Undergraduate,YES,NaN,YES
10,manufacturer11,FENS,Undeclared,Undergraduate,YES,NaN,NaN
11,manufacturer12,FENS,freshman,Undergraduate,NaN,NaN,NaN
12,manufacturer13,SOM,Freshman,Undergraduate,NaN,NaN,NaN
13,manufacturer14,SOM,Undeclared,Undergraduate,YES,NaN,NaN
14,manufacturer15,FENS,MS,Undergraduate,YES,NaN,NaN
15,manufacturer16,FASS,Manufacturing Engineering,Undergraduate,YES,NaN,NaN
16,manufacturer17,FENS,MS,Undergraduate,YES,NaN,NaN
17,manufacturer18,FENS,Manufacturing Systems,Undergraduate,YES,NaN,NaN
18,manufacturer19,SOM,Manufacturing Systems,Undergraduate,YES,NaN,NaN
19,manufacturer20,FASS,Sanat Sosyal Bilimler,Undergraduate,YES,NaN,NaN
20,manufacturer21,FENS,MS,Undergraduate,YES,NaN,NaN
21,manufacturer22,FENS,Manufacturing Science,Undergraduate,YES,NaN,NaN
22,retailer1,SOM,I have not declare yet,Undergraduate,YES,NaN,NaN
23,retailer2,FENS,Computing engineering,Undergraduate,YES,NaN,NaN
24,retailer3,FENS,biological sciences and bioengineering,Undergraduate,YES,NaN,NaN
25,retailer4,SOM,Management,Undergraduate,YES,NaN,YES
26,retailer5,SOM,MBA,MS/MA,NaN,NaN,YES
27,retailer6,SOM,Management,Undergraduate,NaN,NaN,YES
28,retailer7,FENS,industrial engineering,Undergraduate,YES,YES,YES
29,retailer8,FENS,MS,Undergraduate,YES,NaN,NaN
30,retailer9,FENS,Manufacturing Systems,Undergraduate,YES,NaN,NaN
31,retailer10,FENS,Manufacturing Engineering,Undergraduate,YES,NaN,YES
32,retailer11,FENS,Mühendislik ve Doğa Bilimleri,Undergraduate,NaN,NaN,NaN
33,retailer12,FENS,MS,Undergraduate,YES,NaN,YES
34,retailer13,FENS,MS,Undergraduate,YES,NaN,NaN
35,retailer14,FENS,FENS,Undergraduate,NaN,NaN,NaN
36,retailer15,FENS,engineering science,Undergraduate,YES,NaN,NaN
37,retailer16,FENS,Undeclared,Undergraduate,NaN,NaN,NaN
38,retailer17,FENS,Manufacturing Systems Engineering,Undergraduate,YES,NaN,NaN
39,retailer18,FENS,Manufacturing system,Undergraduate,YES,NaN,NaN
40,retailer19,FENS,MS,Undergraduate,YES,NaN,YES
41,retailer20,SOM,Mechatronics Engineering,Undergraduate,YES,NaN,NaN
42,retailer21,FENS,manufacturing system,Undergraduate,YES,NaN,NaN
43,retailer22,FENS,endustri,Undergraduate,YES,NaN,NaN

In [16]:
faculty = pd.get_dummies(default_contract['Faculty'])
faculty = faculty.replace({True: 1, False: 0})
faculty.columns = ['faculty_' + col for col in faculty.columns]
default_contract = pd.concat([default_contract, faculty], axis=1)
default_contract.drop(["Faculty"], axis=1,inplace = True)

In [17]:
program = pd.get_dummies(default_contract['Program'])
program = program.replace({True: 1, False: 0, })
program.columns = ['program_' + col for col in program.columns]
default_contract = pd.concat([default_contract, program], axis=1)
default_contract.drop(["Program"], axis=1,inplace = True)

In [18]:
Grad_Undergrad = pd.get_dummies(default_contract['Grad/ Undergrad'])
Grad_Undergrad = Grad_Undergrad.replace({True: 1, False: 0})
Grad_Undergrad.columns = ['Grad_Undergrad_' + col for col in Grad_Undergrad.columns]
default_contract = pd.concat([default_contract, Grad_Undergrad], axis=1)
default_contract.drop(["Grad/ Undergrad"], axis=1,inplace = True)

In [19]:
default_contract["ENS 208"] = default_contract["ENS 208"].replace({"YES": 1, np.nan: 0}).astype(int)
default_contract["MS 401"] = default_contract["MS 401"].replace({"YES": 1, np.nan: 0}).astype(int)
default_contract["Other Supply Chain Course?"] = default_contract["Other Supply Chain Course?"].replace({"YES": 1, np.nan: 0}).astype(int)
default_contract

,PLAYER NAME,ENS 208,MS 401,Other Supply Chain Course?,faculty_FASS,faculty_FENS,faculty_SOM,program_Computing engineering,program_FENS,program_Freshman,...,program_endustri,program_engineering science,program_freshman,program_industrial engineering,program_manufacturing system,program_mekatronics engineering,program_ms,program_undeclared,Grad_Undergrad_MS/MA,Grad_Undergrad_Undergraduate
0,manufacturer1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,manufacturer2,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,manufacturer3,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,manufacturer4,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,manufacturer5,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,manufacturer6,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,manufacturer7,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,manufacturer8,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
8,manufacturer9,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
9,manufacturer10,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10,manufacturer11,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,manufacturer12,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
12,manufacturer13,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
13,manufacturer14,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
14,manufacturer15,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
15,manufacturer16,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,manufacturer17,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17,manufacturer18,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,manufacturer19,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,manufacturer20,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20,manufacturer21,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21,manufacturer22,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
22,retailer1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23,retailer2,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
24,retailer3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,retailer4,1,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26,retailer5,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
27,retailer6,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
28,retailer7,1,1,1,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
29,retailer8,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
30,retailer9,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
31,retailer10,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
32,retailer11,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
33,retailer12,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
34,retailer13,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
35,retailer14,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
36,retailer15,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
37,retailer16,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
38,retailer17,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
39,retailer18,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
40,retailer19,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
41,retailer20,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
42,retailer21,1,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
43,retailer22,1,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1

In [20]:
default_contract.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 38 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   PLAYER NAME                                     44 non-null     object
 1   ENS 208                                         44 non-null     int64
 2   MS 401                                          44 non-null     int64
 3   Other Supply Chain Course?                      44 non-null     int64
 4   faculty_FASS                                    44 non-null     int64
 5   faculty_FENS                                    44 non-null     int64
 6   faculty_SOM                                     44 non-null     int64
 7   program_Computing engineering                   44 non-null     int64
 8   program_FENS                                    44 non-null     int64
 9   program_Freshman                                44 non-null     int64
 10  program_Have not decleration yet.               44 non-null     int64
 11  program_Henuz yok                               44 non-null     int64
 12  program_I have not declare yet                  44 non-null     int64
 13  program_MBA                                     44 non-null     int64
 14  program_MECHATRONICS                            44 non-null     int64
 15  program_MS                                      44 non-null     int64
 16  program_Management                              44 non-null     int64
 17  program_Manufacturing Engineering               44 non-null     int64
 18  program_Manufacturing Science                   44 non-null     int64
 19  program_Manufacturing System Engineering        44 non-null     int64
 20  program_Manufacturing Systems                   44 non-null     int64
 21  program_Manufacturing Systems Engineering       44 non-null     int64
 22  program_Manufacturing system                    44 non-null     int64
 23  program_Mechatronics Engineering                44 non-null     int64
 24  program_Mühendislik ve Doğa Bilimleri           44 non-null     int64
 25  program_Sanat Sosyal Bilimler                   44 non-null     int64
 26  program_Undeclared                              44 non-null     int64
 27  program_biological sciences and bioengineering  44 non-null     int64
 28  program_endustri                                44 non-null     int64
 29  program_engineering science                     44 non-null     int64
 30  program_freshman                                44 non-null     int64
 31  program_industrial engineering                  44 non-null     int64
 32  program_manufacturing system                    44 non-null     int64
 33  program_mekatronics engineering                 44 non-null     int64
 34  program_ms                                      44 non-null     int64
 35  program_undeclared                              44 non-null     int64
 36  Grad_Undergrad_MS/MA                            44 non-null     int64
 37  Grad_Undergrad_Undergraduate                    44 non-null     int64
dtypes: int64(37), object(1)
memory usage: 13.2+ KB

In [21]:
default_contract.to_csv('../../Datasets/default_contract_subject_background_information.csv', index=False)