In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
personality = pd.read_excel("../../Datasets/Personality Survey Data.xlsx")

In [3]:
revenue_sharing_contract = personality.iloc[100:144, :]
revenue_sharing_contract = revenue_sharing_contract.iloc[:,2:]
revenue_sharing_contract.columns = personality.iloc[50, 2:]
revenue_sharing_contract.reset_index(drop=True, inplace = True)

In [4]:
faculty = pd.get_dummies(revenue_sharing_contract['Faculty'])
faculty = faculty.replace({True: 1, False: 0})
faculty.columns = ['faculty_' + col for col in faculty.columns]
revenue_sharing_contract = pd.concat([revenue_sharing_contract, faculty], axis=1)
revenue_sharing_contract.drop(["Faculty"], axis=1,inplace = True)

In [5]:
program = pd.get_dummies(revenue_sharing_contract['Program'])
program = program.replace({True: 1, False: 0, })
program.columns = ['program_' + col for col in program.columns]
revenue_sharing_contract = pd.concat([revenue_sharing_contract, program], axis=1)
revenue_sharing_contract.drop(["Program"], axis=1,inplace = True)

In [6]:
Grad_Undergrad = pd.get_dummies(revenue_sharing_contract['Grad/ Undergrad'])
Grad_Undergrad = Grad_Undergrad.replace({True: 1, False: 0})
Grad_Undergrad.columns = ['Grad_Undergrad_' + col for col in Grad_Undergrad.columns]
revenue_sharing_contract = pd.concat([revenue_sharing_contract, Grad_Undergrad], axis=1)
revenue_sharing_contract.drop(["Grad/ Undergrad"], axis=1,inplace = True)

In [7]:
revenue_sharing_contract["ENS 208"] = revenue_sharing_contract["ENS 208"].replace({"YES": 1, np.nan: 0}).astype(int)
revenue_sharing_contract["MS 401"] = revenue_sharing_contract["MS 401"].replace({"YES": 1, np.nan: 0}).astype(int)
revenue_sharing_contract["Other Supply Chain Course?"] = revenue_sharing_contract["Other Supply Chain Course?"].replace({"YES": 1, np.nan: 0}).astype(int)
revenue_sharing_contract

,PLAYER NAME,ENS 208,MS 401,Other Supply Chain Course?,faculty_FASS,faculty_FENS,faculty_SOM,program_(ERASMUS),program_BIO,program_ECON,...,program_IE,program_MAN,program_MAT,program_MBA,program_MSIE,program_Turkish Studies,Grad_Undergrad_MS/MA,Grad_Undergrad_PREP,Grad_Undergrad_PhD,Grad_Undergrad_Undergrad
0,manufacturer1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,manufacturer2,1,0,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,manufacturer3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,manufacturer4,1,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
4,manufacturer5,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,manufacturer6,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,manufacturer7,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
7,manufacturer8,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,1
8,manufacturer9,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9,manufacturer10,1,0,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
10,manufacturer11,0,0,1,0,1,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
11,manufacturer12,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12,manufacturer13,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
13,manufacturer14,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
14,manufacturer15,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
15,manufacturer16,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,manufacturer17,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17,manufacturer18,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,manufacturer19,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,manufacturer20,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
20,manufacturer21,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
21,manufacturer22,1,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
22,retailer1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23,retailer2,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
24,retailer3,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
25,retailer4,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26,retailer5,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
27,retailer6,1,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
28,retailer7,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
29,retailer8,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
30,retailer9,1,1,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
31,retailer10,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32,retailer11,0,1,1,0,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
33,retailer12,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
34,retailer13,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
35,retailer14,0,0,1,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,1
36,retailer15,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
37,retailer16,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
38,retailer17,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
39,retailer18,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
40,retailer19,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
41,retailer20,0,0,1,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,1
42,retailer21,1,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
43,retailer22,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [8]:
revenue_sharing_contract.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PLAYER NAME                 44 non-null     object
 1   ENS 208                     44 non-null     int64
 2   MS 401                      44 non-null     int64
 3   Other Supply Chain Course?  44 non-null     int64
 4   faculty_FASS                44 non-null     int64
 5   faculty_FENS                44 non-null     int64
 6   faculty_SOM                 44 non-null     int64
 7   program_(ERASMUS)           44 non-null     int64
 8   program_BIO                 44 non-null     int64
 9   program_ECON                44 non-null     int64
 10  program_ECON (ERASMUS)      44 non-null     int64
 11  program_EE                  44 non-null     int64
 12  program_IE                  44 non-null     int64
 13  program_IE                  44 non-null     int64
 14  program_MAN                 44 non-null     int64
 15  program_MAT                 44 non-null     int64
 16  program_MBA                 44 non-null     int64
 17  program_MSIE                44 non-null     int64
 18  program_Turkish Studies     44 non-null     int64
 19  Grad_Undergrad_MS/MA        44 non-null     int64
 20  Grad_Undergrad_PREP         44 non-null     int64
 21  Grad_Undergrad_PhD          44 non-null     int64
 22  Grad_Undergrad_Undergrad    44 non-null     int64
dtypes: int64(22), object(1)
memory usage: 8.0+ KB

In [9]:

revenue_sharing_contract.to_csv('../../Datasets/revenue_sharing_contract_subject_background_information.csv', index=False)