In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
personality = pd.read_excel("../../Datasets/Personality Survey Data.xlsx")

In [3]:
standing_contract = personality.iloc[202:246, :]
standing_contract = standing_contract.iloc[:,2:]
standing_contract.columns = personality.iloc[50, 2:]
standing_contract.reset_index(drop=True, inplace = True)

In [4]:
faculty = pd.get_dummies(standing_contract['Faculty'])
faculty = faculty.replace({True: 1, False: 0})
faculty.columns = ['faculty_' + col for col in faculty.columns]
standing_contract = pd.concat([standing_contract, faculty], axis=1)
standing_contract.drop(["Faculty"], axis=1,inplace = True)

In [5]:
program = pd.get_dummies(standing_contract['Program'])
program = program.replace({True: 1, False: 0, })
program.columns = ['program_' + col for col in program.columns]
standing_contract = pd.concat([standing_contract, program], axis=1)
standing_contract.drop(["Program"], axis=1,inplace = True)

In [6]:
Grad_Undergrad = pd.get_dummies(standing_contract['Grad/ Undergrad'])
Grad_Undergrad = Grad_Undergrad.replace({True: 1, False: 0})
Grad_Undergrad.columns = ['Grad_Undergrad_' + col for col in Grad_Undergrad.columns]
standing_contract = pd.concat([standing_contract, Grad_Undergrad], axis=1)
standing_contract.drop(["Grad/ Undergrad"], axis=1,inplace = True)

In [7]:
standing_contract["ENS 208"] = standing_contract["ENS 208"].replace({"YES": 1, np.nan: 0}).astype(int)
standing_contract["MS 401"] = standing_contract["MS 401"].replace({"YES": 1, np.nan: 0}).astype(int)
standing_contract["Other Supply Chain Course?"] = standing_contract["Other Supply Chain Course?"].replace({"YES": 1, np.nan: 0}).astype(int)
standing_contract

,PLAYER NAME,ENS 208,MS 401,Other Supply Chain Course?,faculty_FASS,faculty_FENS,faculty_SOM,program_CS,program_Electronics Engineering,program_Endüstri Mühendisliği,...,program_engineering,program_freshman,program_manufacturing system,program_manufacturing systems,program_mechactronics,program_ms,program_mühendislik ve doğa bilimleri,program_not decided,program_undeclared,Grad_Undergrad_Undergraduate
0,manufacturer1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,manufacturer2,1,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,manufacturer3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,manufacturer4,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
4,manufacturer5,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,manufacturer6,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,manufacturer7,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,manufacturer8,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,manufacturer9,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,manufacturer10,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
10,manufacturer11,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,manufacturer12,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12,manufacturer13,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
13,manufacturer14,1,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
14,manufacturer15,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
15,manufacturer16,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,manufacturer17,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
17,manufacturer18,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,manufacturer19,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,manufacturer20,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20,manufacturer21,1,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
21,manufacturer22,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
22,retailer1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23,retailer10,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24,retailer11,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,retailer12,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26,retailer13,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
27,retailer14,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
28,retailer15,1,0,1,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
29,retailer16,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
30,retailer17,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
31,retailer18,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
32,retailer19,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
33,retailer2,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
34,retailer20,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
35,retailer21,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
36,retailer22,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
37,retailer3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
38,retailer4,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
39,retailer5,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
40,retailer6,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
41,retailer7,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
42,retailer8,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
43,retailer9,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [8]:
standing_contract.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 37 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   PLAYER NAME                                      44 non-null     object
 1   ENS 208                                          44 non-null     int64
 2   MS 401                                           44 non-null     int64
 3   Other Supply Chain Course?                       44 non-null     int64
 4   faculty_FASS                                     44 non-null     int64
 5   faculty_FENS                                     44 non-null     int64
 6   faculty_SOM                                      44 non-null     int64
 7   program_CS                                       44 non-null     int64
 8   program_Electronics Engineering                  44 non-null     int64
 9   program_Endüstri Mühendisliği                    44 non-null     int64
 10  program_Engineering faculty and natural science  44 non-null     int64
 11  program_FEN bilimleri                            44 non-null     int64
 12  program_MS                                       44 non-null     int64
 13  program_MS(expected)                             44 non-null     int64
 14  program_Manifacturing Systems                    44 non-null     int64
 15  program_Manufacturing Science (most probably)    44 non-null     int64
 16  program_Manufacturing Systems Engineering        44 non-null     int64
 17  program_Manufacturing system                     44 non-null     int64
 18  program_Manufacturing systems                    44 non-null     int64
 19  program_Mechatronics                             44 non-null     int64
 20  program_Mekatronik                               44 non-null     int64
 21  program_Mekatronik Mühendisliği                  44 non-null     int64
 22  program_Not Declared                             44 non-null     int64
 23  program_Sophomore                                44 non-null     int64
 24  program_Undeclared                               44 non-null     int64
 25  program_Yönetim Bilimleri                        44 non-null     int64
 26  program_computer science                         44 non-null     int64
 27  program_engineering                              44 non-null     int64
 28  program_freshman                                 44 non-null     int64
 29  program_manufacturing system                     44 non-null     int64
 30  program_manufacturing systems                    44 non-null     int64
 31  program_mechactronics                            44 non-null     int64
 32  program_ms                                       44 non-null     int64
 33  program_mühendislik ve doğa bilimleri            44 non-null     int64
 34  program_not decided                              44 non-null     int64
 35  program_undeclared                               44 non-null     int64
 36  Grad_Undergrad_Undergraduate                     44 non-null     int64
dtypes: int64(36), object(1)
memory usage: 12.8+ KB

In [9]:
standing_contract.to_csv('../../Datasets/standing_contract_subject_background_information.csv', index=False)