In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
personality = pd.read_excel("../../Datasets/Personality Survey Data.xlsx")

In [3]:
standing_decisions = personality.iloc[253:299, :]
standing_decisions = standing_decisions.iloc[:,2:]
standing_decisions.columns = personality.iloc[50, 2:]
standing_decisions.reset_index(drop=True, inplace = True)

In [4]:
standing_decisions

50,PLAYER NAME,Faculty,Program,Grad/ Undergrad,ENS 208,MS 401,Other Supply Chain Course?
0,manufacturer1,FENS,MA,Undergraduate,YES,NaN,NaN
1,manufacturer2,SOM,Sophomore,Undergraduate,YES,NaN,NaN
2,manufacturer3,FENS,Mühendislik ve Doğa Billimleri Programı,Undergraduate,YES,NaN,NaN
3,manufacturer4,FENS,Üretim Mühendisliği,Undergraduate,YES,NaN,NaN
4,manufacturer5,FENS,MS,Undergraduate,YES,NaN,NaN
5,manufacturer6,FENS,Electronics,Undergraduate,NaN,NaN,NaN
6,manufacturer7,SOM,MS,Undergraduate,YES,NaN,NaN
7,manufacturer8,FENS,Computer Engineer,Undergraduate,NaN,NaN,NaN
8,manufacturer9,FENS,manufacturing systems,Undergraduate,YES,NaN,NaN
9,manufacturer10,FENS,Mühendislik ve Doğa Bilimleri,Undergraduate,YES,NaN,NaN
10,manufacturer11,FASS,Endüstri,Undergraduate,YES,NaN,NaN
11,manufacturer12,FENS,Industrial Engineering,Undergraduate,YES,NaN,NaN
12,manufacturer13,FASS,undeclared,Undergraduate,YES,NaN,YES
13,manufacturer14,FASS,Manufacturing Engineering,Undergraduate,YES,NaN,NaN
14,manufacturer15,FENS,MS,Undergraduate,YES,NaN,NaN
15,manufacturer16,FENS,Endüstri/Bilgisayar Mühendisliği,Undergraduate,YES,NaN,NaN
16,manufacturer17,FENS,Endüstri Mühendisliği,Undergraduate,YES,NaN,NaN
17,manufacturer18,FENS,Manufacturing Systems,Undergraduate,YES,NaN,NaN
18,manufacturer19,FENS,Undeclared,Undergraduate,YES,NaN,NaN
19,manufacturer20,FENS,Undeclared,Undergraduate,YES,NaN,NaN
20,manufacturer21,FENS,Computer Science,Undergraduate,YES,NaN,NaN
21,manufacturer22,FENS,haven't chosen yet Ms or Cs,Undergraduate,YES,NaN,NaN
22,retailer1,FENS,Ms,Undergraduate,YES,NaN,NaN
23,retailer2,FENS,Not declared,Undergraduate,YES,NaN,YES
24,retailer3,FENS,Manufacturing Engineering,Undergraduate,YES,NaN,NaN
25,retailer4,FENS,Endüstri Mühendisliği,Undergraduate,YES,NaN,NaN
26,retailer5,FENS,ms,Undergraduate,YES,NaN,NaN
27,retailer6,FENS,msıe,Undergraduate,YES,NaN,NaN
28,retailer7,FENS,Üretim sistemleri,Undergraduate,YES,NaN,NaN
29,retailer8,FENS,Manifacturing Engineering,Undergraduate,YES,NaN,NaN
30,retailer9,FENS,Manufacturing systems engineering,Undergraduate,YES,NaN,NaN
31,retailer10,FENS,Ms,Undergraduate,YES,NaN,NaN
32,retailer11,FENS,Üretim Mühendisligi,Undergraduate,YES,NaN,NaN
33,retailer12,FENS,manufacturing systems engineering,Undergraduate,YES,NaN,NaN
34,retailer13,FENS,MDBF,Undergraduate,YES,NaN,NaN
35,retailer14,FENS,Mekatronik,Undergraduate,YES,NaN,NaN
36,retailer15,FASS,MS,Undergraduate,YES,NaN,NaN
37,retailer16,FENS,Undeclared,Undergraduate,YES,NaN,NaN
38,retailer17,FENS,Manufacturing Systems,Undergraduate,YES,NaN,YES
39,retailer18,FASS,MS,Undergraduate,YES,NaN,NaN
40,retailer19,FENS,Undeclared,Undergraduate,YES,NaN,NaN
41,retailer20,FENS,MS,Undergraduate,YES,NaN,NaN
42,retailer21,FENS,MS,Undergraduate,YES,NaN,NaN
43,retailer22,FENS,Manufacturing Systems,Undergraduate,YES,NaN,NaN

In [5]:
faculty = pd.get_dummies(standing_decisions['Faculty'])
faculty = faculty.replace({True: 1, False: 0})
faculty.columns = ['faculty_' + col for col in faculty.columns]
standing_decisions = pd.concat([standing_decisions, faculty], axis=1)
standing_decisions.drop(["Faculty"], axis=1,inplace = True)

In [6]:
program = pd.get_dummies(standing_decisions['Program'])
program = program.replace({True: 1, False: 0, })
program.columns = ['program_' + col for col in program.columns]
standing_decisions = pd.concat([standing_decisions, program], axis=1)
standing_decisions.drop(["Program"], axis=1,inplace = True)

In [7]:
Grad_Undergrad = pd.get_dummies(standing_decisions['Grad/ Undergrad'])
Grad_Undergrad = Grad_Undergrad.replace({True: 1, False: 0})
Grad_Undergrad.columns = ['Grad_Undergrad_' + col for col in Grad_Undergrad.columns]
standing_decisions = pd.concat([standing_decisions, Grad_Undergrad], axis=1)
standing_decisions.drop(["Grad/ Undergrad"], axis=1,inplace = True)

In [8]:
standing_decisions["ENS 208"] = standing_decisions["ENS 208"].replace({"YES": 1, np.nan: 0}).astype(int)
standing_decisions["MS 401"] = standing_decisions["MS 401"].replace({"YES": 1, np.nan: 0}).astype(int)
standing_decisions["Other Supply Chain Course?"] = standing_decisions["Other Supply Chain Course?"].replace({"YES": 1, np.nan: 0}).astype(int)
standing_decisions

,PLAYER NAME,ENS 208,MS 401,Other Supply Chain Course?,faculty_FASS,faculty_FENS,faculty_SOM,program_Computer Engineer,program_Computer Science,program_Electronics,...,program_haven't chosen yet Ms or Cs,program_manufacturing systems,program_manufacturing systems engineering,program_ms,program_msıe,program_undeclared,program_Üretim Mühendisligi,program_Üretim Mühendisliği,program_Üretim sistemleri,Grad_Undergrad_Undergraduate
0,manufacturer1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,manufacturer2,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,manufacturer3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,manufacturer4,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
4,manufacturer5,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,manufacturer6,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
6,manufacturer7,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,manufacturer8,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
8,manufacturer9,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
9,manufacturer10,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10,manufacturer11,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,manufacturer12,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12,manufacturer13,1,0,1,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
13,manufacturer14,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
14,manufacturer15,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
15,manufacturer16,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,manufacturer17,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
17,manufacturer18,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
18,manufacturer19,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,manufacturer20,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20,manufacturer21,1,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
21,manufacturer22,1,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
22,retailer1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23,retailer2,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
24,retailer3,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,retailer4,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
26,retailer5,1,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
27,retailer6,1,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
28,retailer7,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
29,retailer8,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
30,retailer9,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
31,retailer10,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
32,retailer11,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
33,retailer12,1,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
34,retailer13,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
35,retailer14,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
36,retailer15,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
37,retailer16,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
38,retailer17,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
39,retailer18,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
40,retailer19,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
41,retailer20,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
42,retailer21,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
43,retailer22,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [9]:
standing_decisions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 38 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   PLAYER NAME                                      44 non-null     object
 1   ENS 208                                          44 non-null     int64
 2   MS 401                                           44 non-null     int64
 3   Other Supply Chain Course?                       44 non-null     int64
 4   faculty_FASS                                     44 non-null     int64
 5   faculty_FENS                                     44 non-null     int64
 6   faculty_SOM                                      44 non-null     int64
 7   program_Computer Engineer                        44 non-null     int64
 8   program_Computer Science                         44 non-null     int64
 9   program_Electronics                              44 non-null     int64
 10  program_Endüstri                                 44 non-null     int64
 11  program_Endüstri Mühendisliği                    44 non-null     int64
 12  program_Endüstri/Bilgisayar Mühendisliği         44 non-null     int64
 13  program_Industrial Engineering                   44 non-null     int64
 14  program_MA                                       44 non-null     int64
 15  program_MDBF                                     44 non-null     int64
 16  program_MS                                       44 non-null     int64
 17  program_Manifacturing Engineering                44 non-null     int64
 18  program_Manufacturing Engineering                44 non-null     int64
 19  program_Manufacturing Systems                    44 non-null     int64
 20  program_Manufacturing systems engineering        44 non-null     int64
 21  program_Mekatronik                               44 non-null     int64
 22  program_Ms                                       44 non-null     int64
 23  program_Mühendislik ve Doğa Bilimleri            44 non-null     int64
 24  program_Mühendislik ve Doğa Billimleri Programı  44 non-null     int64
 25  program_Not declared                             44 non-null     int64
 26  program_Sophomore                                44 non-null     int64
 27  program_Undeclared                               44 non-null     int64
 28  program_haven't chosen yet Ms or Cs              44 non-null     int64
 29  program_manufacturing systems                    44 non-null     int64
 30  program_manufacturing systems engineering        44 non-null     int64
 31  program_ms                                       44 non-null     int64
 32  program_msıe                                     44 non-null     int64
 33  program_undeclared                               44 non-null     int64
 34  program_Üretim Mühendisligi                      44 non-null     int64
 35  program_Üretim Mühendisliği                      44 non-null     int64
 36  program_Üretim sistemleri                        44 non-null     int64
 37  Grad_Undergrad_Undergraduate                     44 non-null     int64
dtypes: int64(37), object(1)
memory usage: 13.2+ KB

In [10]:
standing_decisions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 38 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   PLAYER NAME                                      44 non-null     object
 1   ENS 208                                          44 non-null     int64
 2   MS 401                                           44 non-null     int64
 3   Other Supply Chain Course?                       44 non-null     int64
 4   faculty_FASS                                     44 non-null     int64
 5   faculty_FENS                                     44 non-null     int64
 6   faculty_SOM                                      44 non-null     int64
 7   program_Computer Engineer                        44 non-null     int64
 8   program_Computer Science                         44 non-null     int64
 9   program_Electronics                              44 non-null     int64
 10  program_Endüstri                                 44 non-null     int64
 11  program_Endüstri Mühendisliği                    44 non-null     int64
 12  program_Endüstri/Bilgisayar Mühendisliği         44 non-null     int64
 13  program_Industrial Engineering                   44 non-null     int64
 14  program_MA                                       44 non-null     int64
 15  program_MDBF                                     44 non-null     int64
 16  program_MS                                       44 non-null     int64
 17  program_Manifacturing Engineering                44 non-null     int64
 18  program_Manufacturing Engineering                44 non-null     int64
 19  program_Manufacturing Systems                    44 non-null     int64
 20  program_Manufacturing systems engineering        44 non-null     int64
 21  program_Mekatronik                               44 non-null     int64
 22  program_Ms                                       44 non-null     int64
 23  program_Mühendislik ve Doğa Bilimleri            44 non-null     int64
 24  program_Mühendislik ve Doğa Billimleri Programı  44 non-null     int64
 25  program_Not declared                             44 non-null     int64
 26  program_Sophomore                                44 non-null     int64
 27  program_Undeclared                               44 non-null     int64
 28  program_haven't chosen yet Ms or Cs              44 non-null     int64
 29  program_manufacturing systems                    44 non-null     int64
 30  program_manufacturing systems engineering        44 non-null     int64
 31  program_ms                                       44 non-null     int64
 32  program_msıe                                     44 non-null     int64
 33  program_undeclared                               44 non-null     int64
 34  program_Üretim Mühendisligi                      44 non-null     int64
 35  program_Üretim Mühendisliği                      44 non-null     int64
 36  program_Üretim sistemleri                        44 non-null     int64
 37  Grad_Undergrad_Undergraduate                     44 non-null     int64
dtypes: int64(37), object(1)
memory usage: 13.2+ KB

In [11]:
standing_decisions.to_csv('../../Datasets/standing_decisions_subject_background_information.csv', index=False)